# Use an appropriate base image
FROM odoo:16
USER root

# Install Git and testing dependencies
RUN apt-get update && apt-get install -y git python3-pip
RUN pip install flake8

# Clone your Odoo module from the repository
RUN git clone https://github.com/haithem-ezee/module_test.git /mnt/extra-addons/your_module

# Run Flake8 to check for linting errors
RUN flake8 /mnt/extra-addons/your_module

# Copy additional addons and custom modules if necessary
COPY ./addons /mnt/extra-addons

# Set up and run Odoo unit tests
# Adjust this section according to your specific test setup
COPY ./tests /opt/tests
RUN python /opt/tests/run_tests.py

# You can set up an entrypoint script or a command to run the tests automatically

