version: '3.8'

services:
  odoo:
    image: odoo:16
    container_name: odoo_container
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db

volumes:
  postgres-data:
  odoo-data:

